# 服务端口
server:
  port: 8222
#服务名称
spring:
  application:
    name: service-gateway
  redis:
    host: 123.56.126.244
    port: 6379
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    password:
  cloud:
    #nacos地址配置
    nacos:
      discovery:
        server-addr: 123.56.126.244:8848
    #使用服务器发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduservice/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduoss/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/eduvod/**
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/educms/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/ucenterservice/**
        - id: service-acl
          uri: http://localhost:8009
          predicates:
            - Path=/admin/acl/**