# 服务端口
server:
  port: 8009

#服务名称


##开启熔断机制
#feign:
#  hystrix:
#    enabled: true
#    commad:
#      default:
#        execution:
#          isolation:
#            thread:
#              timeoutInMilliseconds: 6000


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mapper xml文件的路径
  mapper-locations: classpath:com/liye/aclservice/mapper/xml/*.xml
