server:
  port: 8002



#  #阿里云 OSS
#  #不同的服务器，地址不同
#aliyun:
#  oss:
#   file:
#     endpoint: oss-cn-beijing.aliyuncs.com
#     keyid: LTAI5tMUx1UayQB6TD1hy5x8
#     keysecret: nHT2yTCkdszdr1HZuMV7d85fOBPFZF
#     bucketname: edu-gulioarent   #bucket可以在控制台创建，也可以使用java代码创建
#
