server:
  port: 8002



  #阿里云 OSS
  #不同的服务器，地址不同
aliyun:
  oss:
   file:
     endpoint: oss-cn-beijing.aliyuncs.com
     keyid: LTAI4G2Ef8mvAuLLaHqhmuyC
     keysecret: FovwHOANrKGUuJzHmY6b1k5inRNKDh
     bucketname: edu-gulioarent   #bucket可以在控制台创建，也可以使用java代码创建
#     urlPrefix: https://edu-gulioarent.oss-cn-beijing.aliyuncs.com

